#!/bin/sh /etc/rc.common

# /root/socat/start-socat.sh
# /etc/init.d/socat

USE_PROCD=1

START=99
STOP=10

start_service() {

    logger -t socat-init "Starting Meshtastic TCP gateway"

    procd_open_instance

    procd_set_param command \
        /root/socat/start-socat.sh

    #procd_set_param respawn

    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}

stop_service() {

    logger -t socat-init "Stopping Meshtastic TCP gateway"
}